### ISSUE TITLE
Yes!   Do this!  

### ISSUE THREAD

**Issue by gbinal** [GSA/api-standards#15]
Great work here.  Please implement it for the agency!

**Comment by bsweger** [comment]
💯 Great idea!

Also, if you're up for self-scheduling a USAspending API usability feedback session: https://airtable.com/shr2ZnMomznkSCYho#04

**Comment by pstingley** [comment]
1. Question: Are all web services RESTful?  What about SOAP based web services?  Should this be scoped
to refer only to RESTful web services?  Even though RESTful web services are popular right now, does
the scope of this document limit other future web services that might not be based on REST?

2.   When people say "RESTful" nowadays, they really mean designing simple, intuitive endpoints that represent unique functions in the API.
Disagree:  When people say "RESTful" these days, they are making a
specific statement about the way the interface works.  IAW REST protocol.

3.  Notifications of updates
Have a simple mechanism for clients to follow changes to the API.
Common ways to do this include a mailing list, or a dedicated developer blog with an RSS feed.

This is a poor idea because it requires people or computers to somehow
know of information from some other source.  Documentation needs to be
atomically related to the service or else the service and its documentation
will become disassociated.  One suggestion is that all documentation be 
located within  the /docs path, available via the get method.

4.  In the section titled: API Endpoints, why are the only verbs allowed:
(e.g. GET or POST)?  There are only 5 verbs in REST. Adding the remaining
 three words verbs goes a long way towards clarifying the set of allowed
terms.


5.  Endpoint URLs should advertise resources, and avoid verbs. 
Disagree:  For 40 years the interface of Internet based services have been the 
operation of the service itself, while documentation has been located
in a /docs directory.  Changing the default behavior of web services
at this stage will break lots of things and will result in unnecessarily
complex coding.

6. The FBOpen link to https://pages.18f.gov/fbopen/ gives a 404: Page not
found error.

7. The FDA example violates the: Avoid single-endpoint APIs. Don't jam multiple operations into the same endpoint with the same HTTP verb. rule

8. Add that a documentation page (preferably in the /docs directory) will be provided so that spiders 
can index all web services throughout the domain.

**Comment by gbinal** [comment]
FYI, I moved your feedback into [its own issue](https://github.com/GSA/api-standards/issues/19), @pstingley.  

Closing this issue.
