### ISSUE TITLE
Assorted feedback

### ISSUE THREAD

**Issue by gbinal** [GSA/api-standards#19]
_Moving [feedback](https://github.com/GSA/api-standards/issues/15#issuecomment-278521784) from @pstingley into its own issue._

------------------------

1. Question: Are all web services RESTful?  What about SOAP based web services?  Should this be scoped
to refer only to RESTful web services?  Even though RESTful web services are popular right now, does
the scope of this document limit other future web services that might not be based on REST?

2.   When people say "RESTful" nowadays, they really mean designing simple, intuitive endpoints that represent unique functions in the API.
Disagree:  When people say "RESTful" these days, they are making a
specific statement about the way the interface works.  IAW REST protocol.

3.  Notifications of updates
Have a simple mechanism for clients to follow changes to the API.
Common ways to do this include a mailing list, or a dedicated developer blog with an RSS feed.

This is a poor idea because it requires people or computers to somehow
know of information from some other source.  Documentation needs to be
atomically related to the service or else the service and its documentation
will become disassociated.  One suggestion is that all documentation be 
located within  the /docs path, available via the get method.

4.  In the section titled: API Endpoints, why are the only verbs allowed:
(e.g. GET or POST)?  There are only 5 verbs in REST. Adding the remaining
 three words verbs goes a long way towards clarifying the set of allowed
terms.

5.  Endpoint URLs should advertise resources, and avoid verbs. 
Disagree:  For 40 years the interface of Internet based services have been the 
operation of the service itself, while documentation has been located
in a /docs directory.  Changing the default behavior of web services
at this stage will break lots of things and will result in unnecessarily
complex coding.

6. The FBOpen link to https://pages.18f.gov/fbopen/ gives a 404: Page not
found error.

7. The FDA example violates the: Avoid single-endpoint APIs. Don't jam multiple operations into the same endpoint with the same HTTP verb. rule

8. Add that a documentation page (preferably in the /docs directory) will be provided so that spiders 
can index all web services throughout the domain.

**Comment by rdgsa** [comment]
Thanks for moving to its own issue Gray. Mr. Stingley provided some great feedback, and some of those have already been addressed in the current version in master.

Some initial thoughts:

#1: I updated the wording at the top to clarify that most of the content is related to REST today, but there is some on SOAP and we would like to add more. (I mentioned this as "help wanted" in our kickoff yesterday.)

#2 Certainly a matter of opinion, but it was not essential to the standards and I removed.

#3 No strong opinion on this (and more on the /docs in #8 below). But to be consistent with our message that our user is the developer (and an application) I think that feedback mechanisms are important.

#4 Good point. I added `PUT, PATCH, DELETE`

#5 We feel pretty strongly about using nouns, not verbs, and a lot of our design recommendations are built on that advice. There may of course be technical limitations in certain sitations.

#6 Link corrected.

#7 I removed the FDA example. That section can probably be beefed up to specifically provide examples on parts of our design. (Will use City Pairs API in future to demonstrate all of these that are possible.)

#8 I appreciate the recommendation about the /docs pointing to documentation. I haven't had a time to try it out on the City Pairs API yet. I am interested if anyone else sees technical constraints on this one. One that occurred to me is that when API doco is hosted externally (as our recommended template will be), the /docs will necessarily be a redirect to an external URL that could change. So we would need to be careful how we implement this so that it doesn't create a tightly coupled constraint in our API. At a minimum, this needs to be done through external configuration so that re-coding or re-deploy of the API is not required.

**Comment by pstingley** [comment]
Yes,

Thank you Gray, for pulling these comments out.  This is a worthy discussion.  

Patrick Stingley
CTO - BLM
(202) 815-3550

**Comment by jcastle** [comment]
Looks like @rdgsa addressed the issue.  Closing unless otherwise need to stay open.
